#
#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    healthcheck:
#      enabled: true
#
spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8888


